[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["nodejs", "npm"] 